- name: Demo on vairables
  hosts: all
  vars:
    URL1: play.google.com
  tasks:
   - name: Print a Variable from Play
     debug:
        msg: URL = {{URL1}} 
   - name: Print variable from File
      debug:
        msg: URL = {{URL2}}