- name: Demo on vairables
  hosts: all
  vars:
    URL1: play.google.com
  vars_files:
     - vars.yml
  tasks:
    - name: Print a Variable from Play
      debug:
         msg: URL = {{URL1}} 
    - name: Print variable from File
      debug:
         msg: URL = {{URL2}}
    - name: Demo on Task level variables
      vars:
         URL3: tasks.google.com
      debug:
         msg: URL = {{URL3}}  
    - name: Print variable from CLI
      debug:
        msg: URL = {{URL5}}       
    - name: Show variable precedence
      vars:
        URL: task.google.com
      debug:
        msg: URL = {{URL}}    

 roles:
    - sample     