- name: Demo on tasks tag
  hosts: all
  tasks:
    - name: Centos
      debug:
        msg: Centos
      tags:
        - centos  

    - name: Ubuntu
      debug:
        msg: Ubuntu
      tags:
        - ubuntu
          
