- name: Install Nginx
  yum:
    name: nginx
    state: present


- name: Download frontend
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_PATH: /usr/share/nginx/html

- name: Copy RoboShop Config file
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: Update Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  ignore_errors: yes

- name: Include Node_exporter
  include_role:
    name: common
    tasks_from: node-exporter