- name: Copy MySQL repo 
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs package
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL Server
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Grab default password
  shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: default_pass

- name: Reset MySQL file
  copy:
    src: reset.sql
    dest: /tmp/reset.sql

- name: Reset MySQL password
  shell: mysql --connect-expired-password -u root -p"{{default_pass.stdout}}" </tmp/reset.sql