- name: Copy MySQL repo 
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs package
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL Server
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check password reset status
  shell: echo 'show databases' | mysql -uroot -pDurgaRoboshop@8
  register: out
  ignore_errors: yes

- name: Grab default password
  shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: default_pass
  when: out.rc != 0

- name: Reset MySQL file
  copy:
    src: reset.sql
    dest: /tmp/reset.sql
  when: out.rc != 0

- name: Reset MySQL password
  shell: mysql --connect-expired-password -u root -p"{{default_pass.stdout}}" </tmp/reset.sql
  when: out.rc != 0

- name: check password validate plugin
  shell: echo "shoe plugins; " | mysql -u root -p"DurgaRoboshop@8" 2>/dev/null | grep -i validate_password 
  register: val_out
  ignore_errors: yes
  
- name: Uninstall password validate plugin
  shell: echo "uninstall plugin validate_password" >/tmp/pass.sql
    mysql -u root -p"DurgaRoboshop@81" </tmp/pass.sql 
  when: val_out.rc == 0

- name: Download mysql Schema
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes 

- name: Load schema
  mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_password: DurgaRoboshop@8
    login_user: root
