- name: download node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{NE_VERSION}}/node_exporter-{{NE_VERSION}}.linux-amd64.tar.gz"
    dest: /opt
    remote_src: yes

- name: create link of prometheus with standard directory name
  ansible.builtin.file:
    src: /opt/node_exporter-{{NE_VERSION}}.linux-amd64
    dest: /opt/node_exporter
    state: link

- name: copy systemd file
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: start node exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
